name: MacOS Validation

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: melusina-org/setup-macports@v1
        with:
          parameters: '.github/macports.yml'
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos # ccache-macos
      - name: Build
        run: |
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build-cmake -j